### ISSUE TITLE
Latex formatting is not possible while texlab and latexindent are running

### ISSUE THREAD

**Issue by pcapiod** [LunarVim/LunarVim#3051]
### Problem description

1. Write some latex text
2. Select a line or a paragraph (Visual mode -> `i p` keybinds)
3. Format the paragraph using `g q` keybinds
4. Error on `textDocument/rangeFormatting is not supported by any of the servers registered for the current buffer`

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

NVIM 0.7.2

### Operating system/version

ArcoLinux

### Steps to reproduce

1. Running Lvim with the config.example.lua is producing the error on my side

### support info

```console
 Language client log: /home/pierre/.cache/lvim/lsp.log
 Detected filetype:   lspinfo
 
 0 client(s) attached to this buffer: 
 
 2 active client(s) not attached to this buffer: 
 
 Client: texlab (id: 1, pid: 49496, bufnr: [12])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Client: texlab (id: 2, pid: 49509, bufnr: [12])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Configured servers list: texlab
```

### Screenshots

![Lvim-2022-09-20_21-23](https://user-images.githubusercontent.com/62664084/191346502-4cb0616f-70b6-4eac-bbbc-5c74895c37b4.png)

**Comment by LostNeophyte** [comment]
It looks like texlab does not support range formatting, you can format the whole document using `<leader> l f`

**Comment by pcapiod** [comment]
> It looks like texlab does not support range formatting, you can format the whole document using `<leader> l f`

That does not work either to modify the formatting.

Recent merge from texlab ([https://github.com/latex-lsp/texlab/pull/797](#797)) tried to fix the issue but did not work in lunarvim. I cannot say for other implementations but I suspect the same behavior.

**Comment by LostNeophyte** [comment]
OK, I'll troubleshoot this later

**Comment by LostNeophyte** [comment]
Just to clarify:
1. You're using the default lvim texlab config(you have nothing related to texlab in your config)
2. You  have `latexindent` installed and `print(vim.fn.executable("latexindent"))` returns 1


what does :LspInfo say when you're in a tex file?

**Comment by pcapiod** [comment]
1. Yes I am using the default config
2. It returns 1 with the lua command.

:LspInfo gives me the following result: 

```
 Language client log: /home/pierre/.local/state/nvim/lsp.log
 Detected filetype:   tex
 
 2 client(s) attached to this buffer: 
 
 Client: texlab (id: 1, pid: nil, bufnr: [14])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Client: texlab (id: 2, pid: nil, bufnr: [14])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Configured servers list: texlab
```

**Comment by LostNeophyte** [comment]
It's weird because I have only 1 texlab attached

**Comment by LostNeophyte** [comment]
Your neovim version should be >=0.8 btw
not sure if that's the cause of this issue

**Comment by LostNeophyte** [comment]
please update this info if it has changed:
```
LunarVim version
master-e4a5fe9

Neovim version (>= 0.7.2)
NVIM 0.7.2
```

**Comment by pcapiod** [comment]
I am using the version last version of neovim (0.8.0) and rolling of LunarVim (rolling-7d57046)

**Comment by LostNeophyte** [comment]
rolling is not updated anymore

**Comment by pcapiod** [comment]
Ok let me change back to the master (stable channel)

**Comment by pcapiod** [comment]
Ok by switching to the master version, I have :

```
 Language client log: /home/pierre/.local/state/nvim/lsp.log
 Detected filetype:   tex
 
 1 client(s) attached to this buffer: 
 
 Client: texlab (id: 1, pid: nil, bufnr: [12])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Configured servers list: texlab
```

**Comment by LostNeophyte** [comment]
Does `SPC l f` work?

**Comment by pcapiod** [comment]
That does not format any line on my side

**Comment by LostNeophyte** [comment]
Any messages/lsp logs related?

**Comment by LostNeophyte** [comment]
try with `lvim.log.level = "debug"`

**Comment by pcapiod** [comment]
It does not print anything related to latex or texlab when I do `SPC l f`

**Comment by LostNeophyte** [comment]
idk what to do to be honest, you can try updating/reinstalling texlab , packersync, :LvimCacheReset

**Comment by pcapiod** [comment]
After much further testing, formatting works and text wrapping works with external latexindent configurations. Thanks a lot !

**Comment by dpo** [comment]
@pcapiod Could you explain what you had to do to make it work? I'm using LunarVim from the `release-1.2` branch. Texlab works well (building, forward/reverse search and chktex). However, `latexindent` does not. I went through the steps above and everything seems to check out (`:lua print(vim.fn.executable("latexindent"))` return `1`, etc.) I can run `latexindent` from the command line. Sadly, I haven't gotten it to work inside LunarVim so far.

**Comment by pcapiod** [comment]
> @pcapiod Could you explain what you had to do to make it work? I'm using LunarVim from the `release-1.2` branch. Texlab works well (building, forward/reverse search and chktex). However, `latexindent` does not. I went through the steps above and everything seems to check out (`:lua print(vim.fn.executable("latexindent"))` return `1`, etc.) I can run `latexindent` from the command line. Sadly, I haven't gotten it to work inside LunarVim so far.

From the documentation, you need to add a file named ".indentconfig.yaml" or "indentconfig.yaml" in your home directory. In this file you will specify all the config file that you want to execute when running `latexindent`
The config file should resembles to this :

```
paths:
- /path/to/this/file/called/latexindent.yaml
```

In the specified directory, you will include the config for latexindent : 

```yaml
# Line breaks
modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    textWrapOptions:
        columns: 120
        multipleSpacesToSingle: 1            
        removeBlockLineBreaks: 1
        blocksFollow:
           headings: 1
           commentOnPreviousLine: 1
           par: 1
           blankLine: 1
           verbatim: 1
           filecontents: 1
           other: '\\\]|\\item(?:\h|\[)'      # regex
        blocksBeginWith:
           A-Z: 1
           a-z: 1
           0-9: 1
           other: 0                           # regex
        blocksEndBefore:
           commentOnOwnLine: 1
           verbatim: 1
           filecontents: 1
           other: '\\begin\{|\\\[|\\end\{'    # regex
        huge: overflow                        # forbid mid-word line breaks
        separator: ""    
```
This will activate line breaks with text width of 120.

Cheers
