### ISSUE TITLE
Some icons not showing (nvim-tree, bufferline, etc.)

### ISSUE THREAD

**Issue by lunacd** [LunarVim/LunarVim#4107]
### Problem description

Lots of icons are not showing properly.

### LunarVim version

release-1.3/neovim-0.9-e823ccb

### Neovim version (>= 0.8.0)

0.9.0

### Terminal name

Windows Terminal

### Operating system/version

Windows 11

### Steps to reproduce

Note: I use NerdFont v3.0.0, so that might be the issue. Because I don't see this issue being tracked on another issue, I might as well just open one.

1. Open lunarvim
2. Open two buffers
3. Open nvim-tree

### Screenshots

![image](https://user-images.githubusercontent.com/35328328/235415636-b74db65f-0a24-4e50-bc31-7c0578a1bfe6.png)

**Comment by kobzar** [comment]
Install nerd fonts in your system, reboot windows.
Select Nerd font in terminal app for example "Hack Nerd Font Mono"
Thats all.
Also try another terminal app like alacritty, kitty.

**Comment by lunacd** [comment]
I am using NF. Notice, for example, that the orbit icon on the bottom left renders properly.

And thanks for recommending other terminal emulators. Kitty unfortunately does not run on Windows. So, here is the reproduction using Alacritty:

![image](https://user-images.githubusercontent.com/35328328/235423337-f0ac1ce3-5912-4cea-a43a-a627bf0f078a.png)

**Comment by kobzar** [comment]
Not all Nerd fonts has needed gplyph. 
try this one for alacritty
```
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono 
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono 
    style: Bold Italic
```
